import { StyleSheet } from "react-native";
import { colors } from "../../styles/colors";
import { fonts, fontSizes } from "../../styles/fonts";
import { spacing, radius } from "../../styles/spacing";

export const styles = StyleSheet.create({
  safe: {
    flex:            1,
    backgroundColor: colors.surface,
  },
  header: {
    flexDirection:     "row",
    alignItems:        "center",
    justifyContent:    "space-between",
    paddingHorizontal: spacing.base,
    paddingTop:        spacing.sm,
    paddingBottom:     spacing.md,
    backgroundColor:   colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontFamily: fonts.bold,
    fontSize:   fontSizes.xl,
    color:      colors.text,
  },
  headerSpacer: {
    width: 40,
  },
  headerAction: {
    fontFamily: fonts.medium,
    fontSize:   fontSizes.base,
    color:      colors.textSecondary,
  },
  headerActionPrimary: {
    color: colors.primary,
  },
  scrollContent: {
    paddingBottom: spacing["2xl"],
  },
  profileCard: {
    backgroundColor:  colors.background,
    marginHorizontal: spacing.base,
    marginTop:        spacing.md,
    marginBottom:     spacing.sm,
    borderRadius:     radius.xl,
    paddingBottom:    spacing.lg,
    elevation:        2,
    shadowColor:      "#000",
    shadowOffset:     { width: 0, height: 1 },
    shadowOpacity:    0.07,
    shadowRadius:     4,
  },
  avatarWrap: {
    alignItems:   "center",
    paddingTop:   spacing["2xl"],
    marginBottom: spacing.lg,
  },
  avatarCircle: {
    width:           96,
    height:          96,
    borderRadius:    48,
    backgroundColor: colors.primary,
    justifyContent:  "center",
    alignItems:      "center",
  },
  avatarInitial: {
    fontFamily: fonts.bold,
    fontSize:   38,
    color:      "#fff",
  },
  cameraOverlay: {
    position:        "absolute",
    bottom:          0,
    right:           0,
    width:           30,
    height:          30,
    borderRadius:    15,
    backgroundColor: colors.primary,
    justifyContent:  "center",
    alignItems:      "center",
    borderWidth:     2,
    borderColor:     colors.background,
  },
  changePhotoHint: {
    fontFamily: fonts.regular,
    fontSize:   fontSizes.xs,
    color:      colors.textMuted,
    marginTop:  spacing.sm,
  },
  info: {
    alignItems:        "center",
    paddingHorizontal: spacing.xl,
    gap:               spacing.xs,
  },
  displayName: {
    fontFamily: fonts.bold,
    fontSize:   fontSizes.xl,
    color:      colors.text,
  },
  username: {
    fontFamily: fonts.regular,
    fontSize:   fontSizes.sm,
    color:      colors.textMuted,
  },
  bio: {
    fontFamily: fonts.regular,
    fontSize:   fontSizes.base,
    color:      colors.textSecondary,
    textAlign:  "center",
    lineHeight: fontSizes.base * 1.5,
    marginTop:  spacing.sm,
  },
  form: {
    paddingHorizontal: spacing.base,
    gap:               spacing.xs,
  },
  label: {
    fontFamily:   fonts.medium,
    fontSize:     fontSizes.sm,
    color:        colors.textSecondary,
    marginTop:    spacing.md,
    marginBottom: 4,
  },
  input: {
    borderWidth:       1.5,
    borderColor:       colors.border,
    borderRadius:      radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical:   spacing.sm,
    fontFamily:        fonts.regular,
    fontSize:          fontSizes.base,
    color:             colors.text,
    backgroundColor:   colors.surface,
  },
  inputMultiline: {
    minHeight:  88,
    paddingTop: spacing.sm,
  },
  charCount: {
    fontFamily: fonts.regular,
    fontSize:   fontSizes.xs,
    color:      colors.textMuted,
    alignSelf:  "flex-end",
    marginTop:  4,
  },
  actions: {
    paddingHorizontal: spacing.base,
    paddingBottom:     spacing["2xl"],
    gap:               spacing.sm,
    marginTop:         spacing.sm,
  },
  actionBtn: {
    flexDirection:     "row",
    alignItems:        "center",
    gap:               spacing.sm,
    paddingVertical:   spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor:   colors.background,
    borderRadius:      radius.xl,
    elevation:         2,
    shadowColor:       "#000",
    shadowOffset:      { width: 0, height: 1 },
    shadowOpacity:     0.07,
    shadowRadius:      4,
  },
  actionText: {
    flex:       1,
    fontFamily: fonts.medium,
    fontSize:   fontSizes.base,
    color:      colors.text,
  },
  logoutBtn: {
    flexDirection:     "row",
    alignItems:        "center",
    justifyContent:    "center",
    gap:               spacing.sm,
    backgroundColor:   colors.background,
    borderRadius:      radius.xl,
    paddingVertical:   spacing.md,
    elevation:         2,
    shadowColor:       "#000",
    shadowOffset:      { width: 0, height: 1 },
    shadowOpacity:     0.07,
    shadowRadius:      4,
  },
  logoutText: {
    fontFamily: fonts.semiBold,
    fontSize:   fontSizes.base,
    color:      colors.error,
  },

  /* Change Password Modal */
  modalOverlay: {
    flex:           1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay,
  },
  modalSheet: {
    backgroundColor:   colors.background,
    borderTopLeftRadius:  radius.xl,
    borderTopRightRadius: radius.xl,
    paddingHorizontal: spacing.base,
    paddingBottom:     spacing["3xl"],
    paddingTop:        spacing.md,
  },
  modalHandle: {
    width:           40,
    height:          4,
    borderRadius:    2,
    backgroundColor: colors.border,
    alignSelf:       "center",
    marginBottom:    spacing.lg,
  },
  modalTitle: {
    fontFamily:   fonts.bold,
    fontSize:     fontSizes.lg,
    color:        colors.text,
    marginBottom: spacing.sm,
  },
  pwField: {
    flexDirection:     "row",
    alignItems:        "center",
    borderWidth:       1.5,
    borderColor:       colors.border,
    borderRadius:      radius.md,
    paddingHorizontal: spacing.md,
    backgroundColor:   colors.surface,
    gap:               spacing.sm,
  },
  pwInput: {
    flex:            1,
    paddingVertical: spacing.sm,
    fontFamily:      fonts.regular,
    fontSize:        fontSizes.base,
    color:           colors.text,
  },
  pwSaveBtn: {
    marginTop:       spacing.xl,
    backgroundColor: colors.primary,
    borderRadius:    radius.md,
    paddingVertical: spacing.md,
    alignItems:      "center",
  },
  pwSaveBtnDisabled: {
    opacity: 0.6,
  },
  pwSaveText: {
    fontFamily: fonts.semiBold,
    fontSize:   fontSizes.base,
    color:      "#fff",
  },
  pwCancelBtn: {
    marginTop:       spacing.sm,
    paddingVertical: spacing.md,
    alignItems:      "center",
  },
  pwCancelText: {
    fontFamily: fonts.medium,
    fontSize:   fontSizes.base,
    color:      colors.textSecondary,
  },
});
